/**
 * Maps country names from the standard TopoJSON / GeoJSON (Natural Earth 110m)
 * to/from the 2-letter ISO region codes returned by the DnsCat API.
 */

export const CODE_TO_GEO_NAME: Record<string, string> = {
  // Asia
  cn: 'China',
  hk: 'China', // In 110m topojson, HK coordinates highlight inside China
  mo: 'China',
  tw: 'Taiwan',
  jp: 'Japan',
  kr: 'South Korea',
  kp: 'North Korea',
  mn: 'Mongolia',
  sg: 'Singapore',
  my: 'Malaysia',
  th: 'Thailand',
  vn: 'Vietnam',
  id: 'Indonesia',
  ph: 'Philippines',
  kh: 'Cambodia',
  la: 'Laos',
  mm: 'Myanmar',
  bn: 'Brunei',
  tl: 'Timor-Leste',
  in: 'India',
  pk: 'Pakistan',
  bd: 'Bangladesh',
  lk: 'Sri Lanka',
  np: 'Nepal',
  bt: 'Bhutan',
  mv: 'Sri Lanka',
  kz: 'Kazakhstan',
  uz: 'Uzbekistan',
  tm: 'Turkmenistan',
  kg: 'Kyrgyzstan',
  tj: 'Tajikistan',
  af: 'Afghanistan',
  ae: 'United Arab Emirates',
  sa: 'Saudi Arabia',
  qa: 'Qatar',
  kw: 'Kuwait',
  om: 'Oman',
  bh: 'Saudi Arabia',
  il: 'Israel',
  tr: 'Turkey',
  ir: 'Iran',
  iq: 'Iraq',
  sy: 'Syria',
  jo: 'Jordan',
  lb: 'Lebanon',
  ps: 'Palestine',
  ye: 'Yemen',
  am: 'Armenia',
  az: 'Azerbaijan',
  ge: 'Georgia',
  cy: 'Cyprus',

  // North America
  us: 'United States of America',
  ca: 'Canada',
  mx: 'Mexico',
  cu: 'Cuba',
  do: 'Dominican Rep.',
  ht: 'Haiti',
  jm: 'Jamaica',
  pr: 'Puerto Rico',
  cr: 'Costa Rica',
  pa: 'Panama',
  gt: 'Guatemala',
  hn: 'Honduras',
  sv: 'El Salvador',
  ni: 'Nicaragua',
  bz: 'Belize',
  bs: 'Bahamas',
  tt: 'Trinidad and Tobago',
  gl: 'Greenland',

  // South America
  br: 'Brazil',
  ar: 'Argentina',
  cl: 'Chile',
  co: 'Colombia',
  pe: 'Peru',
  ve: 'Venezuela',
  ec: 'Ecuador',
  bo: 'Bolivia',
  py: 'Paraguay',
  uy: 'Uruguay',
  gy: 'Guyana',
  sr: 'Suriname',
  fk: 'Falkland Is.',

  // Europe
  de: 'Germany',
  gb: 'United Kingdom',
  fr: 'France',
  it: 'Italy',
  es: 'Spain',
  nl: 'Netherlands',
  pl: 'Poland',
  se: 'Sweden',
  ch: 'Switzerland',
  no: 'Norway',
  fi: 'Finland',
  dk: 'Denmark',
  be: 'Belgium',
  at: 'Austria',
  pt: 'Portugal',
  gr: 'Greece',
  cz: 'Czechia',
  ro: 'Romania',
  hu: 'Hungary',
  ie: 'Ireland',
  ua: 'Ukraine',
  ru: 'Russia',
  by: 'Belarus',
  bg: 'Bulgaria',
  hr: 'Croatia',
  sk: 'Slovakia',
  si: 'Slovenia',
  lt: 'Lithuania',
  lv: 'Latvia',
  ee: 'Estonia',
  is: 'Iceland',
  al: 'Albania',
  rs: 'Serbia',
  ba: 'Bosnia and Herz.',
  me: 'Montenegro',
  mk: 'Macedonia',
  md: 'Moldova',
  lu: 'Luxembourg',
  xk: 'Kosovo',

  // Oceania
  au: 'Australia',
  nz: 'New Zealand',
  pg: 'Papua New Guinea',
  fj: 'Fiji',
  sb: 'Solomon Is.',
  vu: 'Vanuatu',
  nc: 'New Caledonia',

  // Africa
  za: 'South Africa',
  eg: 'Egypt',
  ng: 'Nigeria',
  ke: 'Kenya',
  et: 'Ethiopia',
  ma: 'Morocco',
  dz: 'Algeria',
  tz: 'Tanzania',
  gh: 'Ghana',
  sd: 'Sudan',
  ss: 'S. Sudan',
  ug: 'Uganda',
  ao: 'Angola',
  mz: 'Mozambique',
  ci: "Côte d'Ivoire",
  cm: 'Cameroon',
  mg: 'Madagascar',
  zw: 'Zimbabwe',
  sn: 'Senegal',
  zm: 'Zambia',
  ml: 'Mali',
  mw: 'Malawi',
  gn: 'Guinea',
  so: 'Somalia',
  cd: 'Dem. Rep. Congo',
  cg: 'Congo',
  rw: 'Rwanda',
  bj: 'Benin',
  tg: 'Togo',
  sl: 'Sierra Leone',
  ly: 'Libya',
  lr: 'Liberia',
  mr: 'Mauritania',
  cf: 'Central African Rep.',
  na: 'Namibia',
  bw: 'Botswana',
  ga: 'Gabon',
  dj: 'Djibouti',
  gq: 'Eq. Guinea',
  ne: 'Niger',
  bf: 'Burkina Faso',
  td: 'Chad',
  er: 'Eritrea',
  bi: 'Burundi',
  ls: 'Lesotho',
  sz: 'eSwatini',
  gm: 'Gambia',
  gw: 'Guinea-Bissau',
  eh: 'W. Sahara',
  aq: 'Antarctica',
  tf: 'Fr. S. Antarctic Lands',
};

export const COUNTRY_NAME_TO_CODE: Record<string, string> = {
  // Direct lowercase mappings
  china: 'cn',
  'united states': 'us',
  'united states of america': 'us',
  usa: 'us',
  japan: 'jp',
  'hong kong': 'hk',
  singapore: 'sg',
  germany: 'de',
  'united kingdom': 'gb',
  australia: 'au',
  canada: 'ca',
  'south korea': 'kr',
  korea: 'kr',
  'north korea': 'kp',
  france: 'fr',
  russia: 'ru',
  'russian federation': 'ru',
  india: 'in',
  brazil: 'br',
  italy: 'it',
  spain: 'es',
  mexico: 'mx',
  indonesia: 'id',
  nigeria: 'ng',
  bangladesh: 'bd',
  pakistan: 'pk',
  turkey: 'tr',
  vietnam: 'vn',
  philippines: 'ph',
  egypt: 'eg',
  ethiopia: 'et',
  congo: 'cg',
  'dem. rep. congo': 'cd',
  'democratic republic of the congo': 'cd',
  iran: 'ir',
  iraq: 'iq',
  thailand: 'th',
  myanmar: 'mm',
  'south africa': 'za',
  tanzania: 'tz',
  kenya: 'ke',
  sudan: 'sd',
  's. sudan': 'ss',
  'south sudan': 'ss',
  algeria: 'dz',
  ukraine: 'ua',
  argentina: 'ar',
  colombia: 'co',
  poland: 'pl',
  morocco: 'ma',
  uzbekistan: 'uz',
  peru: 'pe',
  angola: 'ao',
  malaysia: 'my',
  mozambique: 'mz',
  ghana: 'gh',
  yemen: 'ye',
  nepal: 'np',
  venezuela: 've',
  madagascar: 'mg',
  cameroon: 'cm',
  niger: 'ne',
  'sri lanka': 'lk',
  'burkina faso': 'bf',
  mali: 'ml',
  malawi: 'mw',
  chile: 'cl',
  kazakhstan: 'kz',
  zambia: 'zm',
  romania: 'ro',
  syria: 'sy',
  guatemala: 'gt',
  ecuador: 'ec',
  senegal: 'sn',
  netherlands: 'nl',
  cambodia: 'kh',
  chad: 'td',
  somalia: 'so',
  somaliland: 'so',
  zimbabwe: 'zw',
  guinea: 'gn',
  rwanda: 'rw',
  benin: 'bj',
  burundi: 'bi',
  tunisia: 'tn',
  bolivia: 'bo',
  belgium: 'be',
  haiti: 'ht',
  cuba: 'cu',
  'dominican republic': 'do',
  'dominican rep.': 'do',
  'czech republic': 'cz',
  czechia: 'cz',
  greece: 'gr',
  jordan: 'jo',
  portugal: 'pt',
  sweden: 'se',
  azerbaijan: 'az',
  hungary: 'hu',
  honduras: 'hn',
  belarus: 'by',
  austria: 'at',
  'papua new guinea': 'pg',
  'sierra leone': 'sl',
  laos: 'la',
  serbia: 'rs',
  togo: 'tg',
  switzerland: 'ch',
  israel: 'il',
  paraguay: 'py',
  bulgaria: 'bg',
  libya: 'ly',
  lebanon: 'lb',
  nicaragua: 'ni',
  kyrgyzstan: 'kg',
  'el salvador': 'sv',
  turkmenistan: 'tm',
  denmark: 'dk',
  finland: 'fi',
  slovakia: 'sk',
  norway: 'no',
  oman: 'om',
  'costa rica': 'cr',
  ireland: 'ie',
  'central african republic': 'cf',
  'central african rep.': 'cf',
  'new zealand': 'nz',
  mauritania: 'mr',
  panama: 'pa',
  kuwait: 'kw',
  croatia: 'hr',
  moldova: 'md',
  georgia: 'ge',
  eritrea: 'er',
  uruguay: 'uy',
  mongolia: 'mn',
  armenia: 'am',
  jamaica: 'jm',
  albania: 'al',
  qatar: 'qa',
  lithuania: 'lt',
  namibia: 'na',
  gambia: 'gm',
  botswana: 'bw',
  gabon: 'ga',
  lesotho: 'ls',
  slovenia: 'si',
  'guinea-bissau': 'gw',
  'equatorial guinea': 'gq',
  'eq. guinea': 'gq',
  latvia: 'lv',
  bahrain: 'bh',
  'trinidad and tobago': 'tt',
  estonia: 'ee',
  'timor-leste': 'tl',
  mauritius: 'mu',
  cyprus: 'cy',
  'n. cyprus': 'cy',
  eswatini: 'sz',
  djibouti: 'dj',
  fiji: 'fj',
  comoros: 'km',
  guyana: 'gy',
  bhutan: 'bt',
  'solomon islands': 'sb',
  'solomon is.': 'sb',
  montenegro: 'me',
  luxembourg: 'lu',
  'western sahara': 'eh',
  'w. sahara': 'eh',
  suriname: 'sr',
  'cape verde': 'cv',
  maldives: 'mv',
  malta: 'mt',
  brunei: 'bn',
  belize: 'bz',
  bahamas: 'bs',
  iceland: 'is',
  vanuatu: 'vu',
  barbados: 'bb',
  'sao tome and principe': 'st',
  samoa: 'ws',
  'saint lucia': 'lc',
  kiribati: 'ki',
  grenada: 'gd',
  'saint vincent and the grenadines': 'vc',
  micronesia: 'fm',
  tonga: 'to',
  seychelles: 'sc',
  'antigua and barbuda': 'ag',
  andorra: 'ad',
  dominica: 'dm',
  'marshall islands': 'mh',
  'saint kitts and nevis': 'kn',
  liechtenstein: 'li',
  monaco: 'mc',
  'san marino': 'sm',
  palau: 'pw',
  tuvalu: 'tv',
  nauru: 'nr',
  vatican: 'va',
  'vatican city': 'va',
  taiwan: 'tw',
  'falkland is.': 'fk',
  greenland: 'gl',
  'fr. s. antarctic lands': 'tf',
  'puerto rico': 'pr',
  "côte d'ivoire": 'ci',
  'cote d\'ivoire': 'ci',
  liberia: 'lr',
  palestine: 'ps',
  'united arab emirates': 'ae',
  afghanistan: 'af',
  tajikistan: 'tj',
  'new caledonia': 'nc',
  'saudi arabia': 'sa',
  antarctica: 'aq',
  uganda: 'ug',
  'bosnia and herz.': 'ba',
  'bosnia and herzegovina': 'ba',
  macedonia: 'mk',
  'north macedonia': 'mk',
  kosovo: 'xk',
};

export const getCountryCodeByName = (name: string): string | undefined => {
  if (!name) return undefined;
  const key = name.toLowerCase().trim();
  return COUNTRY_NAME_TO_CODE[key];
};

export const getGeoNameByCode = (code: string): string | undefined => {
  if (!code) return undefined;
  return CODE_TO_GEO_NAME[code.toLowerCase().trim()];
};
